[workspace] 
channels = ["https://prefix.dev/conda-forge", "https://prefix.dev/motion-stack"]
name = "gogo_keyboard"
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies] 
python = "*"
gogo_keyboard = { path = "."}

[tasks] 
start = "python3 -m gogo_keyboard.example"

# [environments]
# jazzy = { features = ["jazzy"] }
#
# [feature.jazzy.tasks]
# node = "python3 -m gogo_keyboard.ros_node"
#
# ### ROS Jazzy ####
# [feature.jazzy]
# channels = ["https://prefix.dev/robostack-jazzy"]
#
# [feature.jazzy.dependencies]
# ros-jazzy-ros-core = "*"
# ros-jazzy-rmw-zenoh-cpp = "*"

[package] 
name = "gogo_keyboard"
version = "0.0.0"

[package.build] 
backend = { name = "pixi-build-python", version = "==0.4.0" }

[package.host-dependencies] 
setuptools = ">=58.2.0"

[package.run-dependencies] 
gogo_keyboard = { path = "."}
python = ">=3.10"
asyncio_for_robotics = ">=1.2.3,<2"
# asyncio_for_robotics = { path = "~/asyncio-for-robotics"}
pysdl2 = ">=0.9.0"
# pysdl2 = { path = "~/py-sdl2-conda-aarch"}
sdl2 = ">=2.0.0"
sdl2_image = ">=2.0.0"
